package com.moviesAPI.services;

import com.moviesAPI.DTO.CharacterDTO;
import com.moviesAPI.DTO.EditCharacterDTO;
import com.moviesAPI.entities.Character;
import com.moviesAPI.entities.Movie;

import com.moviesAPI.repositories.CharacterRepository;
import com.moviesAPI.repositories.MovieRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.util.List;
import java.util.Optional;

@Service
public class CharacterServices {
    @Autowired // This means to get the bean called characterRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CharacterRepository characterRepository;
    @Autowired
    private MovieRepository movieRepository;

    public void createCharacter(CharacterDTO characterDTO,MultipartFile file) {

        Character character = new Character();
        character.setWeight(characterDTO.getWeight());
        character.setStory(characterDTO.getStory());
        character.setAge(characterDTO.getAge());
        character.setName(characterDTO.getName());
        try {
            character.setImage(file.getBytes());
        } catch (IOException e) {
            e.printStackTrace();
        }
        //only previously added movies will be added to character
        if (characterDTO.getMoviesIds() != null) {
            addMovies(character, characterDTO.getMoviesIds());
        }
        characterRepository.save(character);
    }
    public Iterable getFilteredCharacterList(Integer age, Integer weight, String name,Long movieId){
        if (age != null) {
            return characterRepository.findByAge(age);
        }
        if (name != null) {
            return characterRepository.findByName(name);
        }
        if (weight != null) {
            return characterRepository.findByWeight(weight);
        }
        if (movieId != null) {
            Optional<Movie> moviesFound = movieRepository.findById(movieId);
            return moviesFound.<Iterable>map(Movie::getCharacters).orElse(null);

        }
        return characterRepository.findBy(); //returns all characters in list view if no params were given
    }
    public boolean editCharacter (EditCharacterDTO characterDTO, MultipartFile file)  {
        Optional<Character> characters = characterRepository.findById(characterDTO.getId());

        if (!characters.isPresent()) {
            return false;
        }
        Character character = characters.get();
        //only previously added movies will be added to character
        if (characterDTO.getMoviesIds() != null) {
            addMovies(character, characterDTO.getMoviesIds());
        }
        if (characterDTO.getName() != null) {
            character.setName(characterDTO.getName());
        }
        if (characterDTO.getStory() != null) {
            character.setStory(characterDTO.getStory());
        }
        if (characterDTO.getAge() != null) {
            character.setAge(characterDTO.getAge());
        }
        if (characterDTO.getWeight() != null) {
            character.setWeight(characterDTO.getWeight());
        }
        if (file != null) {
            try {
                character.setImage(file.getBytes());
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        characterRepository.save(character);
        return true;
    }
    public boolean deleteCharacter (Long id) {
        Optional<Character> character = characterRepository.findById(id);
        if (!character.isPresent()) {
            return false;
        }
        characterRepository.delete(character.get());
        return true;
    }
    public Character getCharacterDetails(Long id) {
        Optional<Character> character = characterRepository.findById(id);
        return character.orElse(null);
    }
    private Character addMovies(Character character ,List<Long> moviesIds){
        for (Long movieId : moviesIds) {
            Optional<Movie> movies = movieRepository.findById(movieId);
            if (movies.isPresent()) {
                Movie movie = movies.get();
                character.getMovies().add(movie);
            }
        }
        return character;
    }
}
