package com.moviesAPI.services;

import com.moviesAPI.entities.Genre;
import com.moviesAPI.entities.Movie;
import com.moviesAPI.repositories.GenreRepository;
import com.moviesAPI.repositories.MovieRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.util.List;
import java.util.Optional;

@Service
public class GenreServices {
    @Autowired // This means to get the bean called genreRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private GenreRepository genreRepository;
    @Autowired
    private MovieRepository movieRepository;
    public void createGenre (String name,List<Long> moviesIds,
                             MultipartFile multipartImage) throws IOException {

        Genre genre = new Genre(name,multipartImage.getBytes());

        if (moviesIds != null) {
            //only previously added movies will be added to genre
            for (Long movieId : moviesIds) {
                Optional<Movie> movies = movieRepository.findById(movieId);
                if (movies.isPresent()) {
                    Movie movie = movies.get();
                    genre.getMovies().add(movie);
                }
            }
        }
        genreRepository.save(genre);
    }
}
