package com.moviesAPI.services;

import com.moviesAPI.DTO.GenreDTO;
import com.moviesAPI.entities.Character;
import com.moviesAPI.entities.Genre;
import com.moviesAPI.entities.Movie;
import com.moviesAPI.repositories.GenreRepository;
import com.moviesAPI.repositories.MovieRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.util.List;
import java.util.Optional;

@Service
public class GenreServices {
    @Autowired // This means to get the bean called genreRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private GenreRepository genreRepository;
    @Autowired
    private MovieRepository movieRepository;
    public void createGenre (GenreDTO genreDTO,
                             MultipartFile file) {

        Genre genre = null;
        try {
            genre = new Genre(genreDTO.getName(),file.getBytes());
        } catch (IOException e) {
            e.printStackTrace();
        }

        if (genreDTO.getMoviesIds() != null) {
            //only previously added movies will be added to genre
            for (Long movieId : genreDTO.getMoviesIds()) {
                Optional<Movie> movies = movieRepository.findById(movieId);
                if (movies.isPresent()) {
                    Movie movie = movies.get();
                    genre.getMovies().add(movie);
                }
            }
        }
        genreRepository.save(genre);
    }

    public boolean deleteGenre(Long id) {
        Optional<Genre> genreFound = genreRepository.findById(id);
        if (!genreFound.isPresent()) {
            return false;
        }
        genreRepository.delete(genreFound.get());
        return true;
    }

    public Genre getGenreDetails(Long id) {
        Optional<Genre> genre = genreRepository.findById(id);
        return genre.orElse(null);
    }
}
