package com.moviesAPI.services;

import com.moviesAPI.DTO.EditMovieDTO;
import com.moviesAPI.DTO.MovieDTO;
import com.moviesAPI.entities.Character;
import com.moviesAPI.entities.Genre;
import com.moviesAPI.entities.Movie;
import com.moviesAPI.repositories.CharacterRepository;
import com.moviesAPI.repositories.GenreRepository;
import com.moviesAPI.repositories.MovieRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;

@Service
public class MovieServices {
    @Autowired // This means to get the bean called characterRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CharacterRepository characterRepository;
    @Autowired
    private MovieRepository movieRepository;
    @Autowired
    private GenreRepository genreRepository;

    public void createMovie (MovieDTO movieDTO,MultipartFile file) {
        Movie movie = new Movie();
        movie.setTitle(movieDTO.getTitle());
        movie.setRating(movieDTO.getRating());
        movie.setReleaseYear(movieDTO.getReleaseYear());
        try {
            movie.setImage(file.getBytes());
        } catch (IOException e) {
            e.printStackTrace();
        }
        //only previously added characters will be added to movie
        if (movieDTO.getCharactersIds() != null) {
            addCharacters(movie,movieDTO.getCharactersIds());
        }
        //only previously added genres will be added to movie
        if (movieDTO.getGenresIds() != null) {
            addGenres(movie,movieDTO.getGenresIds());
        }
        movieRepository.save(movie);
    }
    public boolean editMovie (EditMovieDTO movieDTO,
                              MultipartFile file) {
        Optional<Movie> movies = movieRepository.findById(movieDTO.getId());

        if (!movies.isPresent()) {
            return false;
        }
        Movie movie = movies.get();
        if (movieDTO.getTitle() != null) {
            movie.setTitle(movieDTO.getTitle());
        }
        if (movieDTO.getReleaseYear() != null) {
            movie.setReleaseYear(movieDTO.getReleaseYear());
        }
        if (movieDTO.getRating() != null) {
            movie.setRating(movieDTO.getRating());
        }

        if (movieDTO.getCharactersIds() != null) {
            movie.setCharacters(new HashSet<>());  //removes previously added characters!
            addCharacters(movie,movieDTO.getCharactersIds());
        }
        if (movieDTO.getGenresIds() != null) {
            movie.setCharacters(new HashSet<>());  //removes previously added genres!
            addGenres(movie,movieDTO.getGenresIds());
        }
        if (file != null) {
            try {
                movie.setImage(file.getBytes());
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        movieRepository.save(movie);
        return true;
    }
    public Iterable getFilteredMoviesList(Long genreId, String title,String orderBy){
        if (title != null) {
            return movieRepository.findByTitle(title);
        }
        if (orderBy != null) {
            return "ASC".equals(orderBy) ? movieRepository.findByOrderByReleaseYearAsc() :
                    movieRepository.findByOrderByReleaseYearDesc();
        }
        if (genreId != null) {
            Optional<Genre> genresFound = genreRepository.findById(genreId);
            return genresFound.<Iterable>map(Genre::getMovies).orElse(null);
        }
        return movieRepository.findBy(); //returns all movies in list view if no params were given
    }
    public boolean deleteMovie (Long id) {
        Optional<Movie> movieFound = movieRepository.findById(id);
        if (!movieFound.isPresent()) {
            return false;
        }
        movieRepository.delete(movieFound.get());
        return true;
    }
    public Movie getMovieDetails(Long id) {
        return movieRepository.findById(id).orElse(null);
    }
    private Movie addGenres( Movie movie , List<Long> genresIds){
        for (Long genreId : genresIds) {
            Optional<Genre> genres = genreRepository.findById(genreId);
            if (genres.isPresent()) {
                Genre genre = genres.get();
                genre.getMovies().add(movie);
            }
        }
        return movie;
    }
    private Movie addCharacters( Movie movie , List<Long> charactersIds){
        for (Long characterId : charactersIds) {
            Optional<Character> characters = characterRepository.findById(characterId);
            if (characters.isPresent()) {
                Character character = characters.get();
                character.getMovies().add(movie);
            }
        }
        return movie;
    }
}
