package com.moviesAPI.moviesAPI.controllers;




import com.moviesAPI.moviesAPI.entities.Character;
import com.moviesAPI.moviesAPI.entities.Movie;
import com.moviesAPI.moviesAPI.repositories.CharacterRepository;
import com.moviesAPI.moviesAPI.repositories.MovieRepository;
import com.moviesAPI.moviesAPI.services.CharacterServices;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Description;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.util.*;

@Controller // This means that this class is a Controller
@Validated
@RequestMapping(path="/characters") // This means URL's start with /characters (after Application path)
public class CharacterController {
    @Autowired // This means to get the bean called characterRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CharacterRepository characterRepository;
    @Autowired
    private MovieRepository movieRepository;
    @Autowired
    private CharacterServices characterServices;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewCharacter (@RequestParam String name,
                                                 @RequestParam String story,
                                                 @RequestParam Integer age,
                                                 @RequestParam Integer weight,
                                                 @RequestParam(required = false) List<Long> moviesIds ,
                                                 @RequestParam MultipartFile multipartImage) throws IOException {

        characterServices.createCharacter(name,story,age,weight,moviesIds,multipartImage);
        return "Saved";
    }
    @PostMapping(path="/edit")
    @Description("Edits any character's field. editing movies removes the previously saved movies!")
    public @ResponseBody ResponseEntity<String> editCharacter (@RequestParam Long id,
                                               @RequestParam(required = false) String name,
                                                 @RequestParam(required = false) String story,
                                                 @RequestParam(required = false) Integer age,
                                                 @RequestParam(required = false) Integer weight,
                                                 @RequestParam(required = false) List<Long> moviesIds ,
                                                 @RequestParam(required = false) MultipartFile multipartImage) throws IOException {

        if (characterServices.editCharacter(id, name, story, age, weight, moviesIds, multipartImage)) {
            return new ResponseEntity<>(
                    "Character updated successfully",
                    HttpStatus.OK);
        } else {
            return new ResponseEntity<>(
                    "Character doesn't exist",
                    HttpStatus.BAD_REQUEST);
        }
    }
    @DeleteMapping(path="/delete")
    public @ResponseBody String deleteCharacter(@RequestParam Long id) {
        Optional<Character> character = characterRepository.findById(id);
        if (!character.isPresent()) {
            return "character not found";
        }
        characterRepository.delete(character.get());
        return "deleted!";
    }
    @GetMapping(path= "/detail")
    public @ResponseBody
    ResponseEntity getCharacterDetail(@RequestParam Long id) {
        Optional<Character> character = characterRepository.findById(id);
        if (character.isPresent()) {
            return new ResponseEntity<>(
                    character.get(),
                    HttpStatus.OK);
        }
        return new ResponseEntity<>(
                "Character doesn't exist",
                HttpStatus.BAD_REQUEST);
    }

    @RequestMapping(method = RequestMethod.GET)
    public @ResponseBody
    Object filterBy(@RequestParam(value = "age",required = false) Integer age,
                    @RequestParam(value = "name",required = false) String name,
                    @RequestParam(value = "weight",required = false) Integer weight,
                    @RequestParam(value = "movieId",required = false) Long movieId) {
        if (age != null) {
            return characterRepository.findByAge(age);
        }
        if (name != null) {
            return characterRepository.findByName(name);
        }
        if (weight != null) {
            return characterRepository.findByWeight(weight);
        }
        if (movieId != null) {
            Optional<Movie> movies = movieRepository.findById(movieId);
            if (movies.isPresent()){
                return movies.get().getCharacters();
            }
        }
        return characterRepository.findBy(); //returns all characters in list view if no params were given
    }
}